FROM node:20-alpine AS build

WORKDIR /app

# Копируем package.json и package-lock.json (если есть)
COPY package.json ./

# Устанавливаем зависимости
RUN npm install --silent

# Копируем исходный код
COPY . .

# Сборка приложения
RUN npm run build

FROM nginx:alpine

# Удаляем дефолтную страницу nginx
RUN rm -rf /usr/share/nginx/html/*

# Копируем собранное приложение
COPY --from=build /app/build /usr/share/nginx/html

# Копируем конфиг nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Порт
EXPOSE 80

# Запуск nginx
CMD ["nginx", "-g", "daemon off;"]